{% set version = "0.3.3" %}

package:
  name: jsonschema-path
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/j/jsonschema-path/jsonschema_path-{{ version }}.tar.gz
  sha256: f02e5481a4288ec062f8e68c808569e427d905bedfecb7f2e4c69ef77957c382

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --ignore-installed
  number: 1

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python {{ python_min }}
  run:
    - pathable >=0.4.1,<0.5.0
    - python >={{ python_min }}
    - pyyaml >=5.1
    - referencing >=0.28.0,<0.36.0
    - requests >=2.31.0,<3.0.0

test:
  imports:
    - jsonschema_path
  commands:
    - pip check
    - mypy -p jsonschema_path
  requires:
    - pip
    - mypy
    - types-pyyaml
    - types-requests
    - python {{ python_min }}

about:
  home: https://github.com/p1c2u/jsonschema-path
  summary: JSONSchema Spec with object-oriented paths
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bollwyvl
