{% set version = "0.3.2" %}

package:
  name: jsonschema-path
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/j/jsonschema-path/jsonschema_path-{{ version }}.tar.gz
  sha256: 4d0dababf341e36e9b91a5fb2a3e3fd300b0150e7fe88df4e55cc8253c5a3989

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --ignore-installed
  number: 0

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python >=3.8
  run:
    - pathable >=0.4.1,<0.5.0
    - python >=3.8.0
    - pyyaml >=5.1
    - referencing >=0.28.0,<0.31.0
    - requests >=2.31.0,<3.0.0

test:
  imports:
    - jsonschema_path
  commands:
    - pip check
    - mypy -p jsonschema_path
  requires:
    - pip
    - mypy
    - types-pyyaml
    - types-requests

about:
  home: https://github.com/p1c2u/jsonschema-path
  summary: JSONSchema Spec with object-oriented paths
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bollwyvl
